

NUM_BRANDS = 2
NUM_DAYS = 5
NUM_POS = 2
NUM_LSTM_STATE = 64
LEARNING_DECAY_STEP_SIZE = 1000
LEARNING_RATE = 0.0001
THRESHOLD_FOR_CLASSIFICATION = 0.5
LEARNING_RATE_DECAY_FACTOR = 0.9
BATCH_SIZE = 64

AVG_NUM_IMP = 5.0

NUM_SAMPLES = 10000

data_path = 'data/simulation_data.tfrecord'
